name: Build LaTeX document

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: scheme-full

      - name: Build LaTeX document
        run: latexmk -pdf -pdflatex="lualatex -interaction=nonstopmode" thesis.tex

      - name: Save pdf to branch
        if: github.ref == 'refs/heads/master'
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add -f thesis.pdf
            git commit -m "Build PDF"
            git push origin master:build --force
